# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class 7geeseCli < Formula
  desc "Export your 7Geese performance data — objectives, 1:1s, recognition, and reviews — as JSON."
  homepage "https://github.com/ekininceleme/7geese-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v0.1.0/7geese-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "1a1f630065e329b71a1ed23003136c59ad50d6bca908990b63de1386df2cb3e0"

      define_method(:install) do
        bin.install "7geese-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v0.1.0/7geese-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "977110f3c3640d04df8d5dcfedfe501afa3e15489ca352166a87b872345283c3"

      define_method(:install) do
        bin.install "7geese-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v0.1.0/7geese-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "1b4c57dd56e42f26dcc84478d886548fbb6d07dcdc2b47a569de6da8f8ab5327"
      define_method(:install) do
        bin.install "7geese-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v0.1.0/7geese-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "92d75444782ee2f4d199b0e8bb67bdc39c851502a1ccb2fc876274c2676e87eb"
      define_method(:install) do
        bin.install "7geese-cli"
      end
    end
  end
end
