# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SevengeeseCli < Formula
  desc "Export your 7Geese performance data — objectives, 1:1s, recognition, and reviews — as JSON."
  homepage "https://github.com/ekininceleme/7geese-cli"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v0.1.6/7geese-cli_0.1.6_darwin_amd64.tar.gz"
      sha256 "ae550eb5f387ee961d09770af2d48ee4ecc813cdcb52561a39d1c37f67621965"

      define_method(:install) do
        bin.install "7geese-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v0.1.6/7geese-cli_0.1.6_darwin_arm64.tar.gz"
      sha256 "e6f87f87e15f123e44881d0d7ce5eb1813e1cf7dcb2128fb34a670adf97db975"

      define_method(:install) do
        bin.install "7geese-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v0.1.6/7geese-cli_0.1.6_linux_amd64.tar.gz"
      sha256 "001f8c423d248f91b501e07c45cf0d63dfc3f510204e00903da382224ba2a5f3"
      define_method(:install) do
        bin.install "7geese-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v0.1.6/7geese-cli_0.1.6_linux_arm64.tar.gz"
      sha256 "417580bd893eb7194d6a41f6fe52e00f6a0efb137bf7261d95df30a459f02640"
      define_method(:install) do
        bin.install "7geese-cli"
      end
    end
  end
end
