# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SevengeeseCli < Formula
  desc "Export your 7Geese performance data — objectives, 1:1s, recognition, and reviews — as JSON."
  homepage "https://github.com/ekininceleme/7geese-cli"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v0.1.1/7geese-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "14324eed87e327eb7c7927b107c633a8043390ad9b30554f71c1983f70f7aa41"

      define_method(:install) do
        bin.install "7geese-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v0.1.1/7geese-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "e598707cf9824b656f818eddf6bebcdc5e247a86f619fa0ccc60399dcf7699fb"

      define_method(:install) do
        bin.install "7geese-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v0.1.1/7geese-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "937272991531bc42c3cdf67d6e2966bb9b81f7d3218a6f06a47ac72c7c758db0"
      define_method(:install) do
        bin.install "7geese-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v0.1.1/7geese-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "f2b3e797b6dccac6b5ef323afb01c1454b9653c4f468ee1a7258c1f919a4ad82"
      define_method(:install) do
        bin.install "7geese-cli"
      end
    end
  end
end
