# This file was generated by GoReleaser. DO NOT EDIT.
cask "sevengeese-cli" do
  version "0.1.28"

  on_macos do
    on_intel do
      sha256 "1b7b3e3f2723025191f425fe9e06ef242390a0d826f7f921e26a710ea0d0a547"
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v#{version}/7geese-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd36dba2d19c6c82ebb5e929319638ca194e98c42b44bb6bb0d295f00e12ddd6"
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v#{version}/7geese-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f012debec6dc7068ce6440be0144926e236d53747ee710f4683964870ab2b99f"
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v#{version}/7geese-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a870e1938cec45a03d0fb1612817c87ecc842b17e26ab840818cc99896545862"
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v#{version}/7geese-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sevengeese-cli"
  desc "Export your 7Geese performance data — objectives, 1:1s, recognition, and reviews — as JSON."
  homepage "https://github.com/ekininceleme/7geese-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "7geese-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/7geese-cli"]
    end
  end

  # No zap stanza required

end
