# This file was generated by GoReleaser. DO NOT EDIT.
cask "sevengeese-cli" do
  version "0.1.9"

  on_macos do
    on_intel do
      sha256 "23b3740c120dc753f8093c039cdb6964704e1fd91079f8766fa2502a8863b6e8"
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v#{version}/7geese-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "53801773b95dc0d59ba136151ef88c3a1f838fe066938570285dc081207e3b64"
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v#{version}/7geese-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f275e866243f6d1518419aa73ad1e52ea3ab63f17aca89259eb62001c941968e"
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v#{version}/7geese-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "332351f678e57f091b0b4d08dfc2f4ba5539327233dbd1954e56d4e1113606f9"
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v#{version}/7geese-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sevengeese-cli"
  desc "Export your 7Geese performance data — objectives, 1:1s, recognition, and reviews — as JSON."
  homepage "https://github.com/ekininceleme/7geese-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "7geese-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/7geese-cli"]
    end
  end

  # No zap stanza required

end
