# This file was generated by GoReleaser. DO NOT EDIT.
cask "sevengeese-cli" do
  version "0.1.12"

  on_macos do
    on_intel do
      sha256 "bbae88d498896e78bf820817133c9bea3f7a46d4c9a605b0f81e89209d799c0f"
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v#{version}/7geese-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cde8c8f9b3ccd5ebc0efe00062e6c152206c3a26f49feea0c3af2f4e134ad3a9"
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v#{version}/7geese-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ba1a12d5c7e23a2ef994eca91826972cea6e3159476c0dc5fc6982f47e36c58a"
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v#{version}/7geese-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d8971023eae963492f974557753fa6c3d68e7739d08fd42d15f5175afb10691"
      url "https://github.com/ekininceleme/7geese-cli/releases/download/v#{version}/7geese-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sevengeese-cli"
  desc "Export your 7Geese performance data — objectives, 1:1s, recognition, and reviews — as JSON."
  homepage "https://github.com/ekininceleme/7geese-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "7geese-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/7geese-cli"]
    end
  end

  # No zap stanza required

end
